# Generated by Django 3.2.16 on 2022-12-28 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='context',
            new_name='content',
        ),
    ]
